### ISSUE TITLE
Release~20.10 not working with JitPack.

### ISSUE THREAD

**Issue by felipebonezi** [play-rconf/play-rconf#3]
@thibaultmeyer we have some problem with the release.
I can't use it over JitPack resolver.

**Comment by thibaultmeyer** [comment]
Hello,

can you post yout project sbt file ?

are the following lines present in your sbt file?

```sbt
resolvers += "jitpack" at "https://jitpack.io"

libraryDependencies += "com.github.play-rconf" %% "play-rconf" % "release~YY.MM"
```

**Comment by felipebonezi** [comment]
@thibaultmeyer The problem was that when we use `"com.github.play-rconf" %% "play-rconf" % "release~20.10"` with two `%` the SBT try to download the artifact using the Scala Version (play-rconf_2.13).

<img width="1223" alt="Captura de Tela 2020-12-03 às 06 48 32" src="https://user-images.githubusercontent.com/1410319/100992972-9091a380-3533-11eb-8b4f-4a1549a0e381.png">

I set to only one `%` and works perfectly.
