### ISSUE TITLE
Scala application loader won't override local config with remote config

### ISSUE THREAD

**Issue by Kontinuation** [play-rconf/play-rconf#9]
For example, `play.http.secret.key` in remote config does not override the default local config, which is `"changeme"`.

This problem is introduced by [commit  158ee4](https://github.com/play-rconf/play-rconf/commit/158ee477bd6f1d959c76018a09b44140ea2cdd23#diff-230a8b96ef2a6721192f8f3faa0b21be086ab8a556ef0c61fa82cdab97e8c033R67), which simply replaced the deprecated `++` method with `withFallback` method, even though these two methods don't have the same semantics.

The correct approach is to swap the operands, so that we treat local configuration as the fallback config:

```
Configuration.apply(this.processAllProviders(localConfiguration.underlying)) withFallback localConfiguration
```

[Java application loader](https://github.com/play-rconf/play-rconf/blob/master/src/main/java/io/playrconf/ApplicationLoaderJava.java#L164-L167) does not have this problem.

**Comment by thibaultmeyer** [comment]
Hello,

Thank you for reporting this error. Indeed, there is a problem with this part of the code. I'm looking to fix it quickly.

**Comment by thibaultmeyer** [comment]
The problem is fixed. Version `22.03` just released.
